# Generated by Django 5.0.6 on 2024-05-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Vendor Name')),
                ('contact_details', models.TextField(verbose_name='Contact Information of Vendor')),
                ('address', models.TextField(verbose_name='Vendor address')),
                ('vendor_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('on_time_delivery_rate', models.FloatField(blank=True, default=0)),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
            ],
        ),
    ]
